import Head from 'next/head'

import Header from "./header";
import Footer from "./footer";


export default function Layout(props: any) {
    const { children } = props;
    return (
        <>
            <Head>
                <title>Bplay</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/FAVICON.png" />
            </Head>
            <Header />

                {children}
                
            <Footer/>
        </>
    )
}